### ISSUE TITLE
doesn't `npm start`

### ISSUE THREAD

**Issue by mLuby** [hzhu/cats#1]
Hey @hzhu `npm install && npm test` works ✅ but when I run `npm start` I get errors:
1. `Cannot find module 'webpack-dev-server'` (in *package.json*).
So I did `npm install --save-dev webpack-dev-server` and in *package.json* replaced `webpack-dev-server` with `../../node_modules/.bin/webpack-dev-server`.
2. Now it says `Cannot find module 'webpack/bin/config-yargs' though I can't find that used anywhere in the codebase.

Could you try building this in a clean environment to make sure it starts?

**Comment by hzhu** [comment]
Hi @mLuby , certainly! I'll try building this in a clean environment and look into this and get back to you.

**Comment by hzhu** [comment]
Hi @mLuby, I think I found the issue. 

I installed a webpack-dev-server as a local dependency, and updated the webpack version. It seems to work now. Thanks for reporting this issue!

**Comment by mLuby** [comment]
Thanks! It works now.
